spring:
  application:
    name: "Todo Manager"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

app:
  name: "Todo Manager"
  version: "2.0.0"

jwt:
  secret: "dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgdGhhdCBpcyBsb25nIGVub3VnaA=="
  expiration: 3600000

security:
  password-pepper: "mySecretPepperValue"

resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        recordExceptions:
          - com.mipt.aleksandrivanovich.second_sem.hw_1.exception.ExternalApiException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
  ratelimiter:
    instances:
      externalApi:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.mipt.aleksandrivanovich: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n traceId=%X{traceId:-}"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,ratelimiters
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: postgres

external:
  api:
    baseUrl: http://localhost:8080
    connect-timeout: 5000
    read-timeout: 10000

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true